/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--background) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-highlight': 'rgb(var(--surface-highlight) / <alpha-value>)',
        primary: 'rgb(var(--primary) / <alpha-value>)',
        'primary-foreground': 'rgb(var(--primary-foreground) / <alpha-value>)',
        muted: 'rgb(var(--muted) / <alpha-value>)',
        border: 'rgb(var(--border) / <alpha-value>)',
        foreground: 'rgb(var(--foreground) / <alpha-value>)',
        white: 'rgb(var(--on-accent) / <alpha-value>)',
        black: 'rgb(var(--overlay-base) / <alpha-value>)',
        blue: {
          300: 'rgb(var(--accent-blue) / <alpha-value>)',
          400: 'rgb(var(--accent-blue) / <alpha-value>)',
          500: 'rgb(var(--accent-blue) / <alpha-value>)',
          600: 'rgb(var(--accent-blue) / <alpha-value>)',
          700: 'rgb(var(--accent-blue) / <alpha-value>)',
          900: 'rgb(var(--accent-blue) / <alpha-value>)',
        },
        green: {
          400: 'rgb(var(--accent-green) / <alpha-value>)',
          500: 'rgb(var(--accent-green) / <alpha-value>)',
          600: 'rgb(var(--accent-green) / <alpha-value>)',
        },
        lime: {
          400: 'rgb(var(--accent-lime) / <alpha-value>)',
          500: 'rgb(var(--accent-lime) / <alpha-value>)',
          600: 'rgb(var(--accent-lime) / <alpha-value>)',
        },
        emerald: {
          400: 'rgb(var(--accent-emerald) / <alpha-value>)',
          500: 'rgb(var(--accent-emerald) / <alpha-value>)',
          600: 'rgb(var(--accent-emerald) / <alpha-value>)',
        },
        yellow: {
          300: 'rgb(var(--accent-yellow) / <alpha-value>)',
          400: 'rgb(var(--accent-yellow) / <alpha-value>)',
          500: 'rgb(var(--accent-yellow) / <alpha-value>)',
          600: 'rgb(var(--accent-yellow) / <alpha-value>)',
        },
        amber: {
          300: 'rgb(var(--accent-amber) / <alpha-value>)',
          400: 'rgb(var(--accent-amber) / <alpha-value>)',
          500: 'rgb(var(--accent-amber) / <alpha-value>)',
          600: 'rgb(var(--accent-amber) / <alpha-value>)',
        },
        orange: {
          500: 'rgb(var(--accent-orange) / <alpha-value>)',
          600: 'rgb(var(--accent-orange) / <alpha-value>)',
        },
        red: {
          300: 'rgb(var(--accent-red) / <alpha-value>)',
          400: 'rgb(var(--accent-red) / <alpha-value>)',
          500: 'rgb(var(--accent-red) / <alpha-value>)',
          600: 'rgb(var(--accent-red) / <alpha-value>)',
          700: 'rgb(var(--accent-red) / <alpha-value>)',
          800: 'rgb(var(--accent-red) / <alpha-value>)',
          900: 'rgb(var(--accent-red) / <alpha-value>)',
        },
        purple: {
          400: 'rgb(var(--accent-purple) / <alpha-value>)',
          500: 'rgb(var(--accent-purple) / <alpha-value>)',
          600: 'rgb(var(--accent-purple) / <alpha-value>)',
        },
        indigo: {
          300: 'rgb(var(--accent-indigo) / <alpha-value>)',
          400: 'rgb(var(--accent-indigo) / <alpha-value>)',
          500: 'rgb(var(--accent-indigo) / <alpha-value>)',
          600: 'rgb(var(--accent-indigo) / <alpha-value>)',
        },
        pink: {
          400: 'rgb(var(--accent-pink) / <alpha-value>)',
        },
        accent: {
          blue: 'rgb(var(--accent-blue) / <alpha-value>)',
          green: 'rgb(var(--accent-green) / <alpha-value>)',
          lime: 'rgb(var(--accent-lime) / <alpha-value>)',
          emerald: 'rgb(var(--accent-emerald) / <alpha-value>)',
          yellow: 'rgb(var(--accent-yellow) / <alpha-value>)',
          amber: 'rgb(var(--accent-amber) / <alpha-value>)',
          orange: 'rgb(var(--accent-orange) / <alpha-value>)',
          red: 'rgb(var(--accent-red) / <alpha-value>)',
          purple: 'rgb(var(--accent-purple) / <alpha-value>)',
          slate: 'rgb(var(--accent-slate) / <alpha-value>)',
          indigo: 'rgb(var(--accent-indigo) / <alpha-value>)',
          pink: 'rgb(var(--accent-pink) / <alpha-value>)',
        },
      },
    },
  },
  plugins: [],
};
