export const cardioTypes = {
  treadmill_walk: { label: 'Treadmill Walk', met: { light: 3.5, moderate: 4.0, vigorous: 4.5 } },
  treadmill_jog: { label: 'Treadmill Jog', met: { light: 6.0, moderate: 7.0, vigorous: 8.0 } },
  treadmill_run: { label: 'Treadmill Run', met: { light: 8.0, moderate: 9.5, vigorous: 11.0 } },
  bike_stationary: { label: 'Stationary Bike', met: { light: 5.5, moderate: 7.0, vigorous: 10.0 } },
  bike_outdoor: { label: 'Outdoor Cycling', met: { light: 6.0, moderate: 8.0, vigorous: 10.0 } },
  elliptical: { label: 'Elliptical', met: { light: 5.0, moderate: 6.5, vigorous: 8.0 } },
  rowing: { label: 'Rowing Machine', met: { light: 4.8, moderate: 7.0, vigorous: 9.5 } },
  swimming: { label: 'Swimming', met: { light: 5.0, moderate: 7.0, vigorous: 9.0 } },
  stairmaster: { label: 'Stairmaster', met: { light: 6.0, moderate: 8.0, vigorous: 9.0 } },
  walking_outdoor: { label: 'Outdoor Walk', met: { light: 2.8, moderate: 3.5, vigorous: 4.3 } },
  walking_hilly: { label: 'Hilly Walk', met: { light: 3.5, moderate: 4.5, vigorous: 5.3 } },
  hiking_daypack: { label: 'Hiking (Daypack)', met: { light: 6.0, moderate: 7.3, vigorous: 8.5 } },
  hiking_backpacking: { label: 'Backpacking', met: { light: 6.5, moderate: 8.0, vigorous: 9.5 } },
  running_trail: { label: 'Trail Running', met: { light: 7.8, moderate: 9.3, vigorous: 11.5 } },
  running_interval: { label: 'Interval Running', met: { light: 8.0, moderate: 10.0, vigorous: 12.0 } },
  spin_class: { label: 'Spin Class', met: { light: 6.5, moderate: 8.5, vigorous: 10.5 } },
  bike_commute: { label: 'Commuter Cycling', met: { light: 4.5, moderate: 6.5, vigorous: 8.0 } },
  mountain_bike: { label: 'Mountain Biking', met: { light: 7.0, moderate: 9.5, vigorous: 11.0 } },
  jump_rope_basic: { label: 'Jump Rope (Basic)', met: { light: 8.0, moderate: 10.0, vigorous: 12.3 } },
  jump_rope_fast: { label: 'Jump Rope (Fast)', met: { light: 10.5, moderate: 12.5, vigorous: 14.5 } },
  rowing_outdoor: { label: 'Outdoor Rowing', met: { light: 6.0, moderate: 7.8, vigorous: 10.0 } },
  kayaking: { label: 'Kayaking', met: { light: 3.5, moderate: 5.0, vigorous: 6.5 } },
  paddleboarding: { label: 'Stand-Up Paddleboarding', met: { light: 3.3, moderate: 4.5, vigorous: 6.0 } },
  swimming_laps: { label: 'Lap Swimming', met: { light: 6.0, moderate: 8.0, vigorous: 10.0 } },
  aqua_aerobics: { label: 'Aqua Aerobics', met: { light: 3.0, moderate: 4.5, vigorous: 5.5 } },
  boxing_bag: { label: 'Heavy Bag Boxing', met: { light: 6.0, moderate: 7.5, vigorous: 9.0 } },
  boxing_sparring: { label: 'Boxing Sparring', met: { light: 8.0, moderate: 9.5, vigorous: 12.0 } },
  kickboxing: { label: 'Kickboxing', met: { light: 7.5, moderate: 9.0, vigorous: 11.5 } },
  martial_arts: { label: 'Martial Arts (Mixed)', met: { light: 7.0, moderate: 8.5, vigorous: 10.5 } },
  dance_cardio: { label: 'Dance Cardio', met: { light: 5.0, moderate: 6.5, vigorous: 8.0 } },
  dance_high: { label: 'High-Impact Dance', met: { light: 6.5, moderate: 8.0, vigorous: 9.5 } },
  zumba: { label: 'Zumba', met: { light: 4.5, moderate: 6.5, vigorous: 7.8 } },
  hiit_bodyweight: { label: 'Bodyweight HIIT', met: { light: 7.5, moderate: 9.5, vigorous: 11.5 } },
  hiit_cycling: { label: 'HIIT Cycling', met: { light: 7.0, moderate: 9.0, vigorous: 11.0 } },
  battle_ropes: { label: 'Battle Ropes', met: { light: 7.0, moderate: 8.5, vigorous: 10.0 } },
  sled_push: { label: 'Sled Push', met: { light: 6.5, moderate: 8.5, vigorous: 10.5 } },
  stair_sprints: { label: 'Stair Sprints', met: { light: 8.0, moderate: 10.0, vigorous: 12.0 } },
  versa_climber: { label: 'VersaClimber', met: { light: 6.5, moderate: 8.5, vigorous: 10.5 } },
  rowing_sprint: { label: 'Rowing Sprint', met: { light: 7.0, moderate: 9.0, vigorous: 11.0 } },
  ski_machine: { label: 'SkiErg', met: { light: 6.0, moderate: 8.0, vigorous: 10.0 } },
  cross_country_ski: { label: 'Cross-Country Skiing', met: { light: 7.0, moderate: 9.0, vigorous: 11.0 } },
  snowshoeing: { label: 'Snowshoeing', met: { light: 5.3, moderate: 7.0, vigorous: 9.0 } },
  speed_skating: { label: 'Speed Skating', met: { light: 8.0, moderate: 10.0, vigorous: 12.5 } },
  inline_skating: { label: 'Inline Skating', met: { light: 6.0, moderate: 7.5, vigorous: 9.5 } },
  rowing_crossfit: { label: 'CrossFit Rowing', met: { light: 6.5, moderate: 8.5, vigorous: 10.0 } },
  cardio_step: { label: 'Step Aerobics', met: { light: 5.5, moderate: 7.0, vigorous: 8.5 } },
  cardio_step_high: { label: 'Step Aerobics (High)', met: { light: 6.5, moderate: 8.0, vigorous: 10.0 } },
  rebounder: { label: 'Rebounder Jumping', met: { light: 4.0, moderate: 5.5, vigorous: 7.0 } },
  speed_rope_tricks: { label: 'Jump Rope (Tricks)', met: { light: 9.0, moderate: 11.0, vigorous: 13.0 } },
  agility_drills: { label: 'Agility Drills', met: { light: 6.0, moderate: 7.5, vigorous: 9.0 } },
  shuttle_runs: { label: 'Shuttle Runs', met: { light: 8.5, moderate: 10.5, vigorous: 12.5 } },
  soccer_drills: { label: 'Soccer Drills', met: { light: 6.5, moderate: 8.0, vigorous: 9.5 } }
};
