// Food database with nutritional information per 100g
// All values are per 100 grams of the food item

export const FOOD_DATABASE = [
  // Proteins - Meat
  {
    id: 'chicken_breast',
    name: 'Chicken Breast',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fats: 3.6,
    },
    portions: [
      { id: 'small', label: 'Small Breast (120g)', grams: 120 },
      { id: 'medium', label: 'Medium Breast (174g)', grams: 174 },
      { id: 'large', label: 'Large Breast (250g)', grams: 250 },
    ],
  },
  {
    id: 'chicken_thigh',
    name: 'Chicken Thigh',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 209,
      protein: 26,
      carbs: 0,
      fats: 10.9,
    },
    portions: [
      { id: 'small_thigh', label: 'Small Thigh (90g)', grams: 90 },
      { id: 'medium_thigh', label: 'Medium Thigh (120g)', grams: 120 },
    ],
  },
  {
    id: 'turkey_breast',
    name: 'Turkey Breast',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 135,
      protein: 30,
      carbs: 0,
      fats: 1,
    },
    portions: [
      { id: 'slice_thick', label: 'Thick Slice (85g / 3oz)', grams: 85 },
      { id: 'slice_thin', label: 'Thin Slice (28g / 1oz)', grams: 28 },
    ],
  },
  {
    id: 'ground_turkey_93_7',
    name: 'Ground Turkey (93/7)',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 170,
      protein: 21,
      carbs: 0,
      fats: 9,
    },
    portions: [
      { id: 'oz_3', label: '3 oz (85g)', grams: 85 },
      { id: 'oz_4', label: '4 oz (113g)', grams: 113 },
    ],
  },
  {
    id: 'ground_beef',
    name: 'Ground Beef (80/20)',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 254,
      protein: 17.2,
      carbs: 0,
      fats: 20,
    },
    portions: [
      { id: 'oz_3', label: '3 oz (85g)', grams: 85 },
      { id: 'patty', label: 'Patty (113g / 4oz)', grams: 113 },
    ],
  },
  {
    id: 'ground_beef_lean',
    name: 'Ground Beef (90/10)',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 176,
      protein: 20,
      carbs: 0,
      fats: 10,
    },
    portions: [
      { id: 'oz_3', label: '3 oz (85g)', grams: 85 },
      { id: 'patty', label: 'Patty (113g / 4oz)', grams: 113 },
    ],
  },
  {
    id: 'steak_sirloin',
    name: 'Sirloin Steak',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 271,
      protein: 25,
      carbs: 0,
      fats: 18,
    },
    portions: [
      { id: 'oz_4', label: '4 oz Steak (113g)', grams: 113 },
      { id: 'oz_6', label: '6 oz Steak (170g)', grams: 170 },
      { id: 'oz_8', label: '8 oz Steak (227g)', grams: 227 },
    ],
  },
  {
    id: 'steak_filet_mignon',
    name: 'Filet Mignon Steak',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 276,
      protein: 24,
      carbs: 0,
      fats: 19,
    },
    portions: [
      { id: 'oz_4', label: '4 oz Steak (113g)', grams: 113 },
      { id: 'oz_6', label: '6 oz Steak (170g)', grams: 170 },
    ],
  },
  {
    id: 'salmon',
    name: 'Salmon',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 208,
      protein: 20,
      carbs: 0,
      fats: 13,
    },
    portions: [
      { id: 'oz_3', label: '3 oz Filet (85g)', grams: 85 },
      { id: 'oz_6', label: '6 oz Filet (170g)', grams: 170 },
    ],
  },
  {
    id: 'tuna',
    name: 'Tuna',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 144,
      protein: 30,
      carbs: 0,
      fats: 1,
    },
    portions: [
      { id: 'oz_3', label: '3 oz (85g)', grams: 85 },
      { id: 'can_drained_5oz', label: '5 oz Can, drained (~142g)', grams: 142 },
    ],
  },
  {
    id: 'tilapia',
    name: 'Tilapia',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 129,
      protein: 26,
      carbs: 0,
      fats: 2.7,
    },
    portions: [{ id: 'filet', label: 'Filet (113g / 4oz)', grams: 113 }],
  },
  {
    id: 'cod',
    name: 'Cod',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 82,
      protein: 18,
      carbs: 0,
      fats: 0.7,
    },
    portions: [{ id: 'filet', label: 'Filet (113g / 4oz)', grams: 113 }],
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 99,
      protein: 24,
      carbs: 0.2,
      fats: 0.3,
    },
    portions: [
      { id: 'shrimp_med', label: 'Medium Shrimp (5g)', grams: 5 },
      { id: 'oz_3', label: '3 oz (85g)', grams: 85 },
    ],
  },
  {
    id: 'pork_chop',
    name: 'Pork Chop',
    category: 'protein',
    subcategory: 'pork',
    per100g: {
      calories: 231,
      protein: 25.7,
      carbs: 0,
      fats: 13.9,
    },
    portions: [
      { id: 'chop_small', label: 'Small Chop (113g)', grams: 113 },
      { id: 'chop_large', label: 'Large Chop (170g)', grams: 170 },
    ],
  },
  {
    id: 'bacon_cooked',
    name: 'Bacon (Cooked)',
    category: 'protein',
    subcategory: 'pork',
    per100g: {
      calories: 541,
      protein: 37,
      carbs: 1.4,
      fats: 42,
    },
    portions: [{ id: 'slice', label: 'Slice (8g)', grams: 8 }],
  },

  // Proteins - Eggs & Dairy
  {
    id: 'eggs_whole',
    name: 'Whole Eggs',
    category: 'protein',
    subcategory: 'eggs',
    per100g: {
      calories: 155,
      protein: 13,
      carbs: 1.1,
      fats: 11,
    },
    portions: [
      { id: 'small', label: 'Small Egg (38g)', grams: 38 },
      { id: 'medium', label: 'Medium Egg (44g)', grams: 44 },
      { id: 'large', label: 'Large Egg (50g)', grams: 50 },
      { id: 'xlarge', label: 'Extra Large Egg (56g)', grams: 56 },
      { id: 'jumbo', label: 'Jumbo Egg (63g)', grams: 63 },
    ],
  },
  {
    id: 'egg_whites',
    name: 'Egg Whites',
    category: 'protein',
    subcategory: 'eggs',
    per100g: {
      calories: 52,
      protein: 11,
      carbs: 0.7,
      fats: 0.2,
    },
    portions: [
      { id: 'tbsp', label: 'Tablespoon (15g)', grams: 15 },
      { id: 'from_large_egg', label: 'Large Egg (33g)', grams: 33 },
      { id: 'half_cup', label: '½ Cup (120g)', grams: 120 },
    ],
  },
  {
    id: 'greek_yogurt',
    name: 'Greek Yogurt (Non-fat)',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 59,
      protein: 10,
      carbs: 3.6,
      fats: 0.4,
    },
    portions: [
      { id: 'container_s', label: 'Small Container (150g)', grams: 150 },
      { id: 'cup', label: 'Cup (227g)', grams: 227 },
    ],
  },
  {
    id: 'cottage_cheese',
    name: 'Cottage Cheese (Low-fat)',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 72,
      protein: 12,
      carbs: 4.3,
      fats: 1,
    },
    portions: [{ id: 'half_cup', label: '½ Cup (113g)', grams: 113 }],
  },
  {
    id: 'milk_whole',
    name: 'Whole Milk',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 61,
      protein: 3.2,
      carbs: 4.8,
      fats: 3.3,
    },
    portions: [
      { id: 'tbsp', label: 'Tablespoon (15g)', grams: 15 },
      { id: 'cup', label: 'Cup (244g)', grams: 244 },
    ],
  },
  {
    id: 'milk_skim',
    name: 'Skim Milk',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 34,
      protein: 3.4,
      carbs: 5,
      fats: 0.1,
    },
    portions: [
      { id: 'tbsp', label: 'Tablespoon (15g)', grams: 15 },
      { id: 'cup', label: 'Cup (245g)', grams: 245 },
    ],
  },
  {
    id: 'milk_almond',
    name: 'Almond Milk (Unsweetened)',
    category: 'protein',
    subcategory: 'dairy-alt',
    per100g: {
      calories: 13,
      protein: 0.4,
      carbs: 0.6,
      fats: 1.1,
    },
    portions: [{ id: 'cup', label: 'Cup (240g)', grams: 240 }],
  },
  {
    id: 'cheese_cheddar',
    name: 'Cheddar Cheese',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 403,
      protein: 25,
      carbs: 1.3,
      fats: 33,
    },
    portions: [
      { id: 'slice', label: 'Slice (28g)', grams: 28 },
      { id: 'cup_shredded', label: 'Cup Shredded (113g)', grams: 113 },
    ],
  },
  {
    id: 'cheese_mozzarella',
    name: 'Mozzarella Cheese',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 280,
      protein: 28,
      carbs: 2.2,
      fats: 17,
    },
    portions: [
      { id: 'slice', label: 'Slice (28g)', grams: 28 },
      { id: 'cup_shredded', label: 'Cup Shredded (113g)', grams: 113 },
    ],
  },
  {
    id: 'cheese_parmesan',
    name: 'Parmesan Cheese',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 431,
      protein: 38,
      carbs: 4.1,
      fats: 29,
    },
    portions: [
      { id: 'tbsp_grated', label: 'Tablespoon, grated (5g)', grams: 5 },
    ],
  },
  {
    id: 'cheese_swiss',
    name: 'Swiss Cheese',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 380,
      protein: 27,
      carbs: 5.4,
      fats: 28,
    },
    portions: [{ id: 'slice', label: 'Slice (28g)', grams: 28 }],
  },

  // Proteins - Plant-Based
  {
    id: 'tofu_firm',
    name: 'Tofu (Firm)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 76,
      protein: 8,
      carbs: 3,
      fats: 5,
    },
    portions: [{ id: 'serving', label: '3 oz Serving (85g)', grams: 85 }],
  },
  {
    id: 'tempeh',
    name: 'Tempeh',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 193,
      protein: 19,
      carbs: 9,
      fats: 11,
    },
    portions: [{ id: 'serving', label: '3 oz Serving (84g)', grams: 84 }],
  },
  {
    id: 'lentils_cooked',
    name: 'Lentils (Cooked)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 116,
      protein: 9,
      carbs: 20,
      fats: 0.4,
    },
    portions: [{ id: 'cup', label: 'Cup (198g)', grams: 198 }],
  },
  {
    id: 'chickpeas_cooked',
    name: 'Chickpeas (Cooked)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 164,
      protein: 9,
      carbs: 27,
      fats: 2.6,
    },
    portions: [{ id: 'cup', label: 'Cup (164g)', grams: 164 }],
  },
  {
    id: 'black_beans_cooked',
    name: 'Black Beans (Cooked)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 132,
      protein: 8.9,
      carbs: 24,
      fats: 0.5,
    },
    portions: [{ id: 'cup', label: 'Cup (172g)', grams: 172 }],
  },
  {
    id: 'kidney_beans_cooked',
    name: 'Kidney Beans (Cooked)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 127,
      protein: 8.7,
      carbs: 23,
      fats: 0.5,
    },
    portions: [{ id: 'cup', label: 'Cup (177g)', grams: 177 }],
  },

  // Carbs - Grains
  {
    id: 'white_rice_cooked',
    name: 'White Rice (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 130,
      protein: 2.7,
      carbs: 28,
      fats: 0.3,
    },
    portions: [
      { id: 'half_cup', label: '½ Cup Cooked (78g)', grams: 78 },
      { id: 'cup', label: 'Cup Cooked (156g)', grams: 156 },
    ],
  },
  {
    id: 'brown_rice_cooked',
    name: 'Brown Rice (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 112,
      protein: 2.6,
      carbs: 24,
      fats: 0.9,
    },
    portions: [
      { id: 'half_cup', label: '½ Cup Cooked (98g)', grams: 98 },
      { id: 'cup', label: '1 Cup Cooked (195g)', grams: 195 },
    ],
  },
  {
    id: 'pasta_cooked',
    name: 'Pasta (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 131,
      protein: 5,
      carbs: 25,
      fats: 1.1,
    },
    portions: [
      { id: 'half_cup', label: '½ Cup Cooked (70g)', grams: 70 },
      { id: 'cup', label: '1 Cup Cooked (140g)', grams: 140 },
    ],
  },
  {
    id: 'quinoa_cooked',
    name: 'Quinoa (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 120,
      protein: 4.4,
      carbs: 21,
      fats: 1.9,
    },
    portions: [
      { id: 'half_cup', label: '½ Cup Cooked (93g)', grams: 93 },
      { id: 'cup', label: '1 Cup Cooked (185g)', grams: 185 },
    ],
  },
  {
    id: 'oats_dry',
    name: 'Oats (Dry)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 389,
      protein: 16.9,
      carbs: 66,
      fats: 6.9,
    },
    portions: [
      { id: 'half_cup', label: '½ Cup (Dry)', grams: 40 },
      { id: 'one_cup', label: '1 Cup (Dry)', grams: 80 },
    ],
  },
  {
    id: 'cereal_corn_flakes',
    name: 'Cereal (Corn Flakes)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 357,
      protein: 7.5,
      carbs: 84,
      fats: 0.4,
    },
    portions: [{ id: 'cup', label: '1 Cup (28g)', grams: 28 }],
  },
  {
    id: 'granola',
    name: 'Granola',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 471,
      protein: 10,
      carbs: 64,
      fats: 20,
    },
    portions: [
      { id: 'quarter_cup', label: '¼ Cup (25g)', grams: 25 },
      { id: 'half_cup', label: '½ Cup (50g)', grams: 50 },
    ],
  },
  {
    id: 'bread_white',
    name: 'White Bread',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 265,
      protein: 9,
      carbs: 49,
      fats: 3.2,
    },
    portions: [
      { id: 'slice', label: '1 Slice', grams: 28 },
      { id: 'two_slices', label: '2 Slices', grams: 56 },
    ],
  },
  {
    id: 'bread_whole_wheat',
    name: 'Whole Wheat Bread',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 247,
      protein: 13,
      carbs: 41,
      fats: 3.4,
    },
    portions: [
      { id: 'slice', label: '1 Slice', grams: 28 },
      { id: 'two_slices', label: '2 Slices', grams: 56 },
    ],
  },
  {
    id: 'bagel_plain',
    name: 'Bagel (Plain)',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 250,
      protein: 10,
      carbs: 49,
      fats: 1.5,
    },
    portions: [{ id: 'bagel', label: 'Bagel (98g)', grams: 98 }],
  },
  {
    id: 'tortilla_flour',
    name: 'Tortilla (Flour)',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 300,
      protein: 8,
      carbs: 50,
      fats: 7,
    },
    portions: [
      { id: 'small_6in', label: 'Small (6")', grams: 35 },
      { id: 'large_10in', label: 'Large (10")', grams: 70 },
    ],
  },
  {
    id: 'tortilla_corn',
    name: 'Tortilla (Corn)',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 218,
      protein: 5.7,
      carbs: 45,
      fats: 2.8,
    },
    portions: [{ id: 'tortilla', label: '1 Tortilla (25g)', grams: 25 }],
  },

  // Carbs - Potatoes & Starchy Veg
  {
    id: 'potato_baked',
    name: 'Baked Potato',
    category: 'carbs',
    subcategory: 'potato',
    per100g: {
      calories: 93,
      protein: 2.5,
      carbs: 21,
      fats: 0.1,
    },
    portions: [
      { id: 'medium', label: 'Medium Potato (173g)', grams: 173 },
      { id: 'large', label: 'Large Potato (299g)', grams: 299 },
    ],
  },
  {
    id: 'sweet_potato',
    name: 'Sweet Potato',
    category: 'carbs',
    subcategory: 'potato',
    per100g: {
      calories: 86,
      protein: 1.6,
      carbs: 20,
      fats: 0.1,
    },
    portions: [{ id: 'medium', label: 'Medium Potato (180g)', grams: 180 }],
  },
  {
    id: 'french_fries_baked',
    name: 'French Fries (Baked)',
    category: 'carbs',
    subcategory: 'potato',
    per100g: {
      calories: 150,
      protein: 2.5,
      carbs: 26,
      fats: 4.5,
    },
    portions: [{ id: 'serving', label: 'Serving (85g)', grams: 85 }],
  },
  {
    id: 'corn_sweet_cooked',
    name: 'Corn (Sweet, Cooked)',
    category: 'carbs',
    subcategory: 'starchy',
    per100g: {
      calories: 86,
      protein: 3.2,
      carbs: 19,
      fats: 1.2,
    },
    portions: [
      { id: 'ear', label: '1 Ear (90g)', grams: 90 },
      { id: 'cup', label: 'Cup (164g)', grams: 164 },
    ],
  },
  {
    id: 'peas_green_cooked',
    name: 'Peas (Green, Cooked)',
    category: 'carbs',
    subcategory: 'starchy',
    per100g: {
      calories: 81,
      protein: 5,
      carbs: 14,
      fats: 0.4,
    },
    portions: [
      { id: 'half_cup', label: '½ Cup (80g)', grams: 80 },
      { id: 'cup', label: 'Cup (160g)', grams: 160 },
    ],
  },

  // Fruits
  {
    id: 'banana',
    name: 'Banana',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 89,
      protein: 1.1,
      carbs: 23,
      fats: 0.3,
    },
    portions: [
      { id: 'small', label: 'Small Banana', grams: 90 },
      { id: 'medium', label: 'Medium Banana', grams: 118 },
      { id: 'large', label: 'Large Banana', grams: 136 },
    ],
  },
  {
    id: 'apple',
    name: 'Apple',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 52,
      protein: 0.3,
      carbs: 14,
      fats: 0.2,
    },
    portions: [
      { id: 'small', label: 'Small Apple (149g)', grams: 149 },
      { id: 'medium', label: 'Medium Apple (182g)', grams: 182 },
      { id: 'large', label: 'Large Apple (223g)', grams: 223 },
    ],
  },
  {
    id: 'orange',
    name: 'Orange',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 47,
      protein: 0.9,
      carbs: 12,
      fats: 0.1,
    },
    portions: [
      { id: 'small', label: 'Small Orange (96g)', grams: 96 },
      { id: 'medium', label: 'Medium Orange (131g)', grams: 131 },
      { id: 'large', label: 'Large Orange (184g)', grams: 184 },
    ],
  },
  {
    id: 'strawberries',
    name: 'Strawberries',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 32,
      protein: 0.7,
      carbs: 8,
      fats: 0.3,
    },
    portions: [{ id: 'cup_whole', label: '1 Cup Whole (144g)', grams: 144 }],
  },
  {
    id: 'blueberries',
    name: 'Blueberries',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 57,
      protein: 0.7,
      carbs: 14,
      fats: 0.3,
    },
    portions: [{ id: 'cup', label: '1 Cup (148g)', grams: 148 }],
  },
  {
    id: 'grapes',
    name: 'Grapes',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 69,
      protein: 0.7,
      carbs: 18,
      fats: 0.2,
    },
    portions: [{ id: 'cup', label: '1 Cup (92g)', grams: 92 }],
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 30,
      protein: 0.6,
      carbs: 8,
      fats: 0.2,
    },
    portions: [
      { id: 'cup_diced', label: '1 Cup Diced (152g)', grams: 152 },
      { id: 'wedge', label: '1 Wedge (286g)', grams: 286 },
    ],
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 50,
      protein: 0.5,
      carbs: 13,
      fats: 0.1,
    },
    portions: [{ id: 'cup_chunks', label: '1 Cup Chunks (165g)', grams: 165 }],
  },
  {
    id: 'mango',
    name: 'Mango',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 60,
      protein: 0.8,
      carbs: 15,
      fats: 0.4,
    },
    portions: [{ id: 'cup_sliced', label: '1 Cup Sliced (165g)', grams: 165 }],
  },
  {
    id: 'raspberries',
    name: 'Raspberries',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 52,
      protein: 1.2,
      carbs: 12,
      fats: 0.7,
    },
    portions: [{ id: 'cup', label: '1 Cup (123g)', grams: 123 }],
  },
  {
    id: 'kiwi',
    name: 'Kiwi',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 61,
      protein: 1.1,
      carbs: 15,
      fats: 0.5,
    },
    portions: [{ id: 'fruit', label: '1 Fruit (69g)', grams: 69 }],
  },

  // Vegetables
  {
    id: 'broccoli',
    name: 'Broccoli',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 34,
      protein: 2.8,
      carbs: 7,
      fats: 0.4,
    },
    portions: [{ id: 'cup_chopped', label: '1 Cup Chopped (91g)', grams: 91 }],
  },
  {
    id: 'spinach',
    name: 'Spinach',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 23,
      protein: 2.9,
      carbs: 3.6,
      fats: 0.4,
    },
    portions: [
      { id: 'cup_raw', label: '1 Cup Raw (30g)', grams: 30 },
      { id: 'cup_cooked', label: '1 Cup Cooked (180g)', grams: 180 },
    ],
  },
  {
    id: 'asparagus',
    name: 'Asparagus',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 20,
      protein: 2.2,
      carbs: 3.9,
      fats: 0.1,
    },
    portions: [{ id: 'spear_4', label: '4 Spears (60g)', grams: 60 }],
  },
  {
    id: 'green_beans',
    name: 'Green Beans',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 31,
      protein: 1.8,
      carbs: 7,
      fats: 0.1,
    },
    portions: [{ id: 'cup', label: '1 Cup (125g)', grams: 125 }],
  },
  {
    id: 'lettuce_romaine',
    name: 'Lettuce (Romaine)',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 17,
      protein: 1.2,
      carbs: 3.3,
      fats: 0.3,
    },
    portions: [
      { id: 'cup_shredded', label: '1 Cup Shredded (47g)', grams: 47 },
    ],
  },
  {
    id: 'lettuce_iceberg',
    name: 'Lettuce (Iceberg)',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 14,
      protein: 0.9,
      carbs: 3,
      fats: 0.1,
    },
    portions: [
      { id: 'cup_shredded', label: '1 Cup Shredded (57g)', grams: 57 },
    ],
  },
  {
    id: 'kale',
    name: 'Kale',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 49,
      protein: 4.3,
      carbs: 9,
      fats: 0.9,
    },
    portions: [{ id: 'cup_raw', label: '1 Cup Raw (67g)', grams: 67 }],
  },
  {
    id: 'carrots',
    name: 'Carrots',
    category: 'vegetables',
    subcategory: 'root',
    per100g: {
      calories: 41,
      protein: 0.9,
      carbs: 10,
      fats: 0.2,
    },
    portions: [
      { id: 'carrot_med', label: '1 Medium Carrot (61g)', grams: 61 },
      { id: 'cup_chopped', label: '1 Cup Chopped (128g)', grams: 128 },
    ],
  },
  {
    id: 'onion',
    name: 'Onion',
    category: 'vegetables',
    subcategory: 'root',
    per100g: {
      calories: 40,
      protein: 1.1,
      carbs: 9,
      fats: 0.1,
    },
    portions: [{ id: 'onion_med', label: '1 Medium Onion (110g)', grams: 110 }],
  },
  {
    id: 'tomatoes',
    name: 'Tomatoes',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 18,
      protein: 0.9,
      carbs: 3.9,
      fats: 0.2,
    },
    portions: [
      { id: 'tomato_med', label: '1 Medium Tomato (123g)', grams: 123 },
    ],
  },
  {
    id: 'bell_pepper',
    name: 'Bell Pepper',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 31,
      protein: 1,
      carbs: 6,
      fats: 0.3,
    },
    portions: [
      { id: 'pepper_med', label: '1 Medium Pepper (119g)', grams: 119 },
    ],
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 15,
      protein: 0.7,
      carbs: 3.6,
      fats: 0.1,
    },
    portions: [
      { id: 'half_cup_sliced', label: '½ Cup Sliced (52g)', grams: 52 },
    ],
  },
  {
    id: 'mushrooms_white',
    name: 'Mushrooms (White)',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 22,
      protein: 3.1,
      carbs: 3.3,
      fats: 0.3,
    },
    portions: [{ id: 'cup_sliced', label: '1 Cup Sliced (96g)', grams: 96 }],
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 17,
      protein: 1.2,
      carbs: 3.1,
      fats: 0.3,
    },
    portions: [
      { id: 'cup_chopped', label: '1 Cup Chopped (124g)', grams: 124 },
    ],
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 25,
      protein: 1.9,
      carbs: 5,
      fats: 0.3,
    },
    portions: [{ id: 'cup', label: '1 Cup (Florets, 107g)', grams: 107 }],
  },

  // Fats
  {
    id: 'avocado',
    name: 'Avocado',
    category: 'fats',
    subcategory: 'fruit',
    per100g: {
      calories: 160,
      protein: 2,
      carbs: 9,
      fats: 15,
    },
    portions: [
      { id: 'half', label: '½ Medium Avocado (68g)', grams: 68 },
      { id: 'whole', label: 'Medium Avocado (136g)', grams: 136 },
    ],
  },
  {
    id: 'olives_black',
    name: 'Olives (Black)',
    category: 'fats',
    subcategory: 'fruit',
    per100g: {
      calories: 115,
      protein: 0.8,
      carbs: 6,
      fats: 11,
    },
    portions: [{ id: 'olive', label: 'Olive (4g)', grams: 4 }],
  },
  {
    id: 'olive_oil',
    name: 'Olive Oil',
    category: 'fats',
    subcategory: 'oil',
    per100g: {
      calories: 884,
      protein: 0,
      carbs: 0,
      fats: 100,
    },
    portions: [{ id: 'tbsp', label: 'Tablespoon (14g)', grams: 14 }],
  },
  {
    id: 'coconut_oil',
    name: 'Coconut Oil',
    category: 'fats',
    subcategory: 'oil',
    per100g: {
      calories: 890,
      protein: 0,
      carbs: 0,
      fats: 100,
    },
    portions: [{ id: 'tbsp', label: 'Tablespoon (14g)', grams: 14 }],
  },
  {
    id: 'butter',
    name: 'Butter',
    category: 'fats',
    subcategory: 'dairy',
    per100g: {
      calories: 717,
      protein: 0.9,
      carbs: 0.1,
      fats: 81,
    },
    portions: [{ id: 'tbsp', label: 'Tablespoon (14g)', grams: 14 }],
  },
  {
    id: 'cream_cheese',
    name: 'Cream Cheese',
    category: 'fats',
    subcategory: 'dairy',
    per100g: {
      calories: 342,
      protein: 6,
      carbs: 4,
      fats: 34,
    },
    portions: [{ id: 'tbsp', label: 'Tablespoon (14g)', grams: 14 }],
  },
  {
    id: 'sour_cream_full_fat',
    name: 'Sour Cream (Full Fat)',
    category: 'fats',
    subcategory: 'dairy',
    per100g: {
      calories: 198,
      protein: 2.4,
      carbs: 4.6,
      fats: 19,
    },
    portions: [{ id: 'tbsp', label: 'Tablespoon (14g)', grams: 14 }],
  },
  {
    id: 'mayonnaise',
    name: 'Mayonnaise',
    category: 'fats',
    subcategory: 'other',
    per100g: {
      calories: 700,
      protein: 1,
      carbs: 0.6,
      fats: 75,
    },
    portions: [{ id: 'tbsp', label: 'Tablespoon (14g)', grams: 14 }],
  },
  {
    id: 'almonds',
    name: 'Almonds',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 579,
      protein: 21,
      carbs: 22,
      fats: 50,
    },
    portions: [{ id: 'oz', label: '1 oz (approx 23 nuts, 28g)', grams: 28 }],
  },
  {
    id: 'peanut_butter',
    name: 'Peanut Butter',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 588,
      protein: 25,
      carbs: 20,
      fats: 50,
    },
    portions: [
      { id: 'tsp', label: 'Teaspoon (5g)', grams: 5 },
      { id: 'tbsp', label: 'Tablespoon (16g)', grams: 16 },
    ],
  },
  {
    id: 'walnuts',
    name: 'Walnuts',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 654,
      protein: 15,
      carbs: 14,
      fats: 65,
    },
    portions: [{ id: 'oz', label: '1 oz (approx 14 halves, 28g)', grams: 28 }],
  },
  {
    id: 'cashews',
    name: 'Cashews',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 553,
      protein: 18,
      carbs: 30,
      fats: 44,
    },
    portions: [{ id: 'oz', label: '1 oz (approx 18 nuts, 28g)', grams: 28 }],
  },
  {
    id: 'pecans',
    name: 'Pecans',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 691,
      protein: 9,
      carbs: 14,
      fats: 72,
    },
    portions: [{ id: 'oz', label: '1 oz (approx 19 halves, 28g)', grams: 28 }],
  },
  {
    id: 'chia_seeds',
    name: 'Chia Seeds',
    category: 'fats',
    subcategory: 'seeds',
    per100g: {
      calories: 486,
      protein: 17,
      carbs: 42,
      fats: 31,
    },
    portions: [{ id: 'tbsp', label: 'Tablespoon (12g)', grams: 12 }],
  },
  {
    id: 'flax_seeds',
    name: 'Flax Seeds',
    category: 'fats',
    subcategory: 'seeds',
    per100g: {
      calories: 534,
      protein: 18,
      carbs: 29,
      fats: 42,
    },
    portions: [{ id: 'tbsp', label: 'Tablespoon (10g)', grams: 10 }],
  },
  {
    id: 'pumpkin_seeds',
    name: 'Pumpkin Seeds',
    category: 'fats',
    subcategory: 'seeds',
    per100g: {
      calories: 559,
      protein: 30,
      carbs: 11,
      fats: 49,
    },
    portions: [{ id: 'oz', label: '1 oz (28g)', grams: 28 }],
  },
  {
    id: 'sunflower_seeds',
    name: 'Sunflower Seeds',
    category: 'fats',
    subcategory: 'seeds',
    per100g: {
      calories: 584,
      protein: 21,
      carbs: 20,
      fats: 51,
    },
    portions: [{ id: 'oz', label: '1 oz (28g)', grams: 28 }],
  },

  // Protein Supplements
  {
    id: 'whey_protein',
    name: 'Whey Protein Powder',
    category: 'supplements',
    subcategory: 'protein',
    per100g: {
      calories: 400,
      protein: 80,
      carbs: 8,
      fats: 5,
    },
    portions: [{ id: 'scoop', label: 'Scoop (30g)', grams: 30 }],
  },
  {
    id: 'casein_protein',
    name: 'Casein Protein Powder',
    category: 'supplements',
    subcategory: 'protein',
    per100g: {
      calories: 360,
      protein: 78,
      carbs: 5,
      fats: 2,
    },
    portions: [{ id: 'scoop', label: 'Scoop (30g)', grams: 30 }],
  },
  {
    id: 'soy_protein_isolate',
    name: 'Soy Protein Isolate',
    category: 'supplements',
    subcategory: 'protein',
    per100g: {
      calories: 335,
      protein: 88,
      carbs: 0.4,
      fats: 0.5,
    },
    portions: [{ id: 'scoop', label: 'Scoop (30g)', grams: 30 }],
  },
  {
    id: 'creatine_monohydrate',
    name: 'Creatine Monohydrate',
    category: 'supplements',
    subcategory: 'other',
    per100g: {
      calories: 0,
      protein: 0,
      carbs: 0,
      fats: 0,
    },
    portions: [{ id: 'serving', label: 'Serving (5g)', grams: 5 }],
  },

  // Proteins - Additional Meats
  {
    id: 'chicken_wings_cooked',
    name: 'Chicken Wings (Cooked)',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 254,
      protein: 24,
      carbs: 0,
      fats: 17,
    },
    portions: [
      { id: 'wing', label: '1 Wing (35g)', grams: 35 },
      { id: 'serving_3_wings', label: '3 Wings (105g)', grams: 105 },
    ],
  },
  {
    id: 'duck_meat',
    name: 'Duck (Meat Only, Roasted)',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 337,
      protein: 19,
      carbs: 0,
      fats: 28,
    },
    portions: [{ id: 'serving_3oz', label: '3 oz Serving (85g)', grams: 85 }],
  },
  {
    id: 'goose_meat',
    name: 'Goose (Meat Only, Roasted)',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 305,
      protein: 29,
      carbs: 0,
      fats: 21,
    },
    portions: [{ id: 'serving_3oz', label: '3 oz Serving (85g)', grams: 85 }],
  },
  {
    id: 'lamb_leg_roasted',
    name: 'Lamb (Leg, Roasted)',
    category: 'protein',
    subcategory: 'lamb',
    per100g: {
      calories: 206,
      protein: 27,
      carbs: 0,
      fats: 10,
    },
    portions: [{ id: 'serving_3oz', label: '3 oz Serving (85g)', grams: 85 }],
  },
  {
    id: 'lamb_shoulder_roasted',
    name: 'Lamb (Shoulder, Roasted)',
    category: 'protein',
    subcategory: 'lamb',
    per100g: {
      calories: 258,
      protein: 25,
      carbs: 0,
      fats: 17,
    },
    portions: [{ id: 'serving_3oz', label: '3 oz Serving (85g)', grams: 85 }],
  },
  {
    id: 'venison',
    name: 'Venison (Deer, Roasted)',
    category: 'protein',
    subcategory: 'game',
    per100g: {
      calories: 158,
      protein: 30,
      carbs: 0,
      fats: 3.2,
    },
    portions: [{ id: 'serving_3oz', label: '3 oz Serving (85g)', grams: 85 }],
  },
  {
    id: 'bison_ground_90_10',
    name: 'Bison (Ground, 90/10)',
    category: 'protein',
    subcategory: 'game',
    per100g: {
      calories: 179,
      protein: 26,
      carbs: 0,
      fats: 8,
    },
    portions: [{ id: 'serving_4oz', label: '4 oz Serving (113g)', grams: 113 }],
  },
  {
    id: 'ham_lean',
    name: 'Ham (Lean)',
    category: 'protein',
    subcategory: 'pork',
    per100g: {
      calories: 145,
      protein: 20,
      carbs: 1.5,
      fats: 6,
    },
    portions: [{ id: 'slice_1oz', label: '1 oz Slice (28g)', grams: 28 }],
  },
  {
    id: 'prosciutto',
    name: 'Prosciutto',
    category: 'protein',
    subcategory: 'pork',
    per100g: {
      calories: 247,
      protein: 26,
      carbs: 0,
      fats: 14,
    },
    portions: [{ id: 'slice', label: '1 Slice (15g)', grams: 15 }],
  },
  {
    id: 'turkey_bacon',
    name: 'Turkey Bacon',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 382,
      protein: 29,
      carbs: 3.1,
      fats: 28,
    },
    portions: [{ id: 'slice', label: '1 Slice (15g)', grams: 15 }],
  },
  {
    id: 'beef_brisket',
    name: 'Beef Brisket (Braised)',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 254,
      protein: 27,
      carbs: 0,
      fats: 16,
    },
    portions: [{ id: 'serving_3oz', label: '3 oz Serving (85g)', grams: 85 }],
  },
  {
    id: 'beef_ribeye',
    name: 'Beef Ribeye (Grilled)',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 291,
      protein: 24,
      carbs: 0,
      fats: 21,
    },
    portions: [{ id: 'steak_6oz', label: '6 oz Steak (170g)', grams: 170 }],
  },
  {
    id: 'beef_round_roast',
    name: 'Beef Round (Roast)',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 210,
      protein: 29,
      carbs: 0,
      fats: 9,
    },
    portions: [{ id: 'serving_3oz', label: '3 oz Serving (85g)', grams: 85 }],
  },

  // Proteins - Fish & Seafood
  {
    id: 'sardines_in_water',
    name: 'Sardines (Canned in Water)',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 208,
      protein: 25,
      carbs: 0,
      fats: 11.5,
    },
  },
  {
    id: 'mackerel',
    name: 'Mackerel (Atlantic)',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 205,
      protein: 19,
      carbs: 0,
      fats: 14,
    },
  },
  {
    id: 'trout',
    name: 'Trout (Rainbow)',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 190,
      protein: 26,
      carbs: 0,
      fats: 8,
    },
  },
  {
    id: 'herring',
    name: 'Herring (Atlantic)',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 158,
      protein: 18,
      carbs: 0,
      fats: 9,
    },
  },
  {
    id: 'anchovies',
    name: 'Anchovies (Canned in Oil, Drained)',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 210,
      protein: 29,
      carbs: 0,
      fats: 10,
    },
  },
  {
    id: 'scallops',
    name: 'Scallops',
    category: 'protein',
    subcategory: 'shellfish',
    per100g: {
      calories: 88,
      protein: 16,
      carbs: 3.2,
      fats: 0.8,
    },
  },
  {
    id: 'mussels',
    name: 'Mussels',
    category: 'protein',
    subcategory: 'shellfish',
    per100g: {
      calories: 172,
      protein: 24,
      carbs: 7.4,
      fats: 4.5,
    },
  },
  {
    id: 'crab',
    name: 'Crab (Blue, Cooked)',
    category: 'protein',
    subcategory: 'shellfish',
    per100g: {
      calories: 97,
      protein: 21,
      carbs: 0,
      fats: 1.5,
    },
  },
  {
    id: 'lobster',
    name: 'Lobster (Cooked)',
    category: 'protein',
    subcategory: 'shellfish',
    per100g: {
      calories: 89,
      protein: 19,
      carbs: 0,
      fats: 1,
    },
  },

  // Proteins - Eggs & Dairy (More)
  {
    id: 'yogurt_plain_lowfat',
    name: 'Yogurt (Plain, Low-Fat)',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 63,
      protein: 5.5,
      carbs: 7,
      fats: 1.6,
    },
  },
  {
    id: 'kefir_plain',
    name: 'Kefir (Plain)',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 52,
      protein: 3.5,
      carbs: 7.2,
      fats: 1,
    },
  },
  {
    id: 'ricotta_part_skim',
    name: 'Ricotta (Part-Skim)',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 138,
      protein: 11.3,
      carbs: 3,
      fats: 8,
    },
  },
  {
    id: 'feta_cheese',
    name: 'Feta Cheese',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 265,
      protein: 14,
      carbs: 4,
      fats: 21,
    },
  },
  {
    id: 'goat_cheese',
    name: 'Goat Cheese (Chevre)',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 364,
      protein: 22,
      carbs: 3,
      fats: 29,
    },
  },
  {
    id: 'yogurt_greek_2percent',
    name: 'Greek Yogurt (2%)',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 73,
      protein: 9.8,
      carbs: 3.6,
      fats: 2,
    },
  },

  // Proteins - Plant-Based (More)
  {
    id: 'edamame',
    name: 'Edamame (Cooked)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 122,
      protein: 11,
      carbs: 10,
      fats: 5,
    },
  },
  {
    id: 'seitan',
    name: 'Seitan (Wheat Gluten)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 370,
      protein: 75,
      carbs: 14,
      fats: 1.9,
    },
  },
  {
    id: 'tofu_silken',
    name: 'Tofu (Silken)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 55,
      protein: 5,
      carbs: 2,
      fats: 3,
    },
  },
  {
    id: 'black_eyed_peas_cooked',
    name: 'Black-Eyed Peas (Cooked)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 116,
      protein: 7.7,
      carbs: 20,
      fats: 0.5,
    },
  },
  {
    id: 'pinto_beans_cooked',
    name: 'Pinto Beans (Cooked)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 143,
      protein: 9,
      carbs: 27,
      fats: 0.7,
    },
  },
  {
    id: 'refried_beans',
    name: 'Refried Beans',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 110,
      protein: 6,
      carbs: 16,
      fats: 3,
    },
  },

  // Carbs - Grains (More)
  {
    id: 'barley_cooked',
    name: 'Barley (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 123,
      protein: 2.3,
      carbs: 28,
      fats: 0.4,
    },
  },
  {
    id: 'bulgur_cooked',
    name: 'Bulgur (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 83,
      protein: 3.1,
      carbs: 19,
      fats: 0.2,
    },
  },
  {
    id: 'couscous_cooked',
    name: 'Couscous (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 112,
      protein: 3.8,
      carbs: 23,
      fats: 0.2,
    },
  },
  {
    id: 'buckwheat_cooked',
    name: 'Buckwheat (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 92,
      protein: 3.4,
      carbs: 20,
      fats: 0.6,
    },
  },
  {
    id: 'millet_cooked',
    name: 'Millet (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 119,
      protein: 3.5,
      carbs: 23.7,
      fats: 1,
    },
  },
  {
    id: 'rye_bread',
    name: 'Rye Bread',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 259,
      protein: 8.5,
      carbs: 48,
      fats: 3.3,
    },
  },
  {
    id: 'sourdough_bread',
    name: 'Sourdough Bread',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 259,
      protein: 8.8,
      carbs: 49,
      fats: 2.3,
    },
  },
  {
    id: 'pita_bread',
    name: 'Pita Bread (White)',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 275,
      protein: 9,
      carbs: 55,
      fats: 1,
    },
  },
  {
    id: 'naan_bread',
    name: 'Naan Bread',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 310,
      protein: 9.2,
      carbs: 53,
      fats: 7.1,
    },
  },
  {
    id: 'rice_cakes_plain',
    name: 'Rice Cakes (Plain)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 387,
      protein: 7.5,
      carbs: 82,
      fats: 3.2,
    },
  },
  {
    id: 'tortilla_whole_wheat',
    name: 'Tortilla (Whole Wheat)',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 250,
      protein: 9,
      carbs: 44,
      fats: 4.5,
    },
  },

  // Carbs - Breakfast Cereals & Oats
  {
    id: 'oats_cooked',
    name: 'Oats (Cooked Porridge)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 71,
      protein: 2.5,
      carbs: 12,
      fats: 1.5,
    },
  },
  {
    id: 'muesli',
    name: 'Muesli (No Added Sugar)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 360,
      protein: 10,
      carbs: 66,
      fats: 6,
    },
  },
  {
    id: 'bran_flakes',
    name: 'Bran Flakes',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 265,
      protein: 9,
      carbs: 80,
      fats: 1.4,
    },
  },

  // Carbs - Starchy Veg (More)
  {
    id: 'yams',
    name: 'Yams',
    category: 'carbs',
    subcategory: 'potato',
    per100g: {
      calories: 118,
      protein: 1.5,
      carbs: 28,
      fats: 0.2,
    },
  },
  {
    id: 'plantain_cooked',
    name: 'Plantain (Boiled)',
    category: 'carbs',
    subcategory: 'starchy',
    per100g: {
      calories: 116,
      protein: 1.3,
      carbs: 31,
      fats: 0.2,
    },
  },
  {
    id: 'taro_cooked',
    name: 'Taro (Cooked)',
    category: 'carbs',
    subcategory: 'starchy',
    per100g: {
      calories: 142,
      protein: 0.5,
      carbs: 35,
      fats: 0.1,
    },
  },

  // Fruits (More)
  {
    id: 'pear',
    name: 'Pear',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 57,
      protein: 0.4,
      carbs: 15,
      fats: 0.1,
    },
  },
  {
    id: 'peach',
    name: 'Peach',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 39,
      protein: 0.9,
      carbs: 10,
      fats: 0.3,
    },
  },
  {
    id: 'plum',
    name: 'Plum',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 46,
      protein: 0.7,
      carbs: 11.4,
      fats: 0.3,
    },
  },
  {
    id: 'apricot',
    name: 'Apricot',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 48,
      protein: 1.4,
      carbs: 11,
      fats: 0.4,
    },
  },
  {
    id: 'cherries',
    name: 'Cherries',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 63,
      protein: 1.1,
      carbs: 16,
      fats: 0.2,
    },
  },
  {
    id: 'blackberries',
    name: 'Blackberries',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 43,
      protein: 1.4,
      carbs: 10,
      fats: 0.5,
    },
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate (Arils)',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 83,
      protein: 1.7,
      carbs: 19,
      fats: 1.2,
    },
  },
  {
    id: 'papaya',
    name: 'Papaya',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 43,
      protein: 0.5,
      carbs: 11,
      fats: 0.3,
    },
  },
  {
    id: 'guava',
    name: 'Guava',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 68,
      protein: 2.6,
      carbs: 14,
      fats: 1,
    },
  },
  {
    id: 'dragonfruit',
    name: 'Dragon Fruit (Pitaya)',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 60,
      protein: 1.2,
      carbs: 13,
      fats: 0.2,
    },
  },
  {
    id: 'lychee',
    name: 'Lychee',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 66,
      protein: 0.8,
      carbs: 17,
      fats: 0.4,
    },
  },
  {
    id: 'avocado_hass',
    name: 'Avocado (Hass)',
    category: 'fats',
    subcategory: 'fruit',
    per100g: {
      calories: 160,
      protein: 2,
      carbs: 9,
      fats: 15,
    },
    portions: [
      { id: 'half_avocado', label: 'Half Avocado (100g)', grams: 100 },
    ],
  },

  // Vegetables (More)
  {
    id: 'brussels_sprouts',
    name: 'Brussels Sprouts',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 43,
      protein: 3.4,
      carbs: 9,
      fats: 0.3,
    },
    portions: [{ id: 'cup_cooked', label: 'Cup (156g)', grams: 156 }],
  },
  {
    id: 'bok_choy',
    name: 'Bok Choy',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 13,
      protein: 1.5,
      carbs: 2.2,
      fats: 0.2,
    },
    portions: [{ id: 'cup_cooked', label: 'Cup (156g)', grams: 156 }],
  },
  {
    id: 'cabbage_green',
    name: 'Cabbage (Green)',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 25,
      protein: 1.3,
      carbs: 6,
      fats: 0.1,
    },
    portions: [{ id: 'cup_cooked', label: 'Cup (156g)', grams: 156 }],
  },
  {
    id: 'red_cabbage',
    name: 'Cabbage (Red)',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 31,
      protein: 1.4,
      carbs: 7,
      fats: 0.2,
    },
    portions: [{ id: 'cup_cooked', label: 'Cup (156g)', grams: 156 }],
  },
  {
    id: 'beets_cooked',
    name: 'Beets (Cooked)',
    category: 'vegetables',
    subcategory: 'root',
    per100g: {
      calories: 44,
      protein: 1.7,
      carbs: 10,
      fats: 0.2,
    },
    portions: [{ id: 'cup_cooked', label: 'Cup (156g)', grams: 156 }],
  },
  {
    id: 'turnip_cooked',
    name: 'Turnip (Cooked)',
    category: 'vegetables',
    subcategory: 'root',
    per100g: {
      calories: 22,
      protein: 0.7,
      carbs: 5,
      fats: 0.1,
    },
    portions: [{ id: 'cup_cooked', label: 'Cup (156g)', grams: 156 }],
  },
  {
    id: 'parsnip_cooked',
    name: 'Parsnip (Cooked)',
    category: 'vegetables',
    subcategory: 'root',
    per100g: {
      calories: 75,
      protein: 1.2,
      carbs: 17,
      fats: 0.3,
    },
    portions: [{ id: 'cup_cooked', label: 'Cup (156g)', grams: 156 }],
  },
  {
    id: 'eggplant',
    name: 'Eggplant',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 25,
      protein: 1,
      carbs: 6,
      fats: 0.2,
    },
    portions: [{ id: 'cup_cooked', label: 'Cup (156g)', grams: 156 }],
  },
  {
    id: 'celery',
    name: 'Celery',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 16,
      protein: 0.7,
      carbs: 3,
      fats: 0.2,
    },
    portions: [{ id: 'cup_chopped', label: 'Cup Chopped (101g)', grams: 101 }],
  },
  {
    id: 'radish',
    name: 'Radish',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 16,
      protein: 0.7,
      carbs: 3.4,
      fats: 0.1,
    },
    portions: [{ id: 'cup_sliced', label: 'Cup Sliced (116g)', grams: 116 }],
  },
  {
    id: 'artichoke',
    name: 'Artichoke',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 47,
      protein: 3.3,
      carbs: 11,
      fats: 0.2,
    },
    portions: [{ id: 'cup_cooked', label: 'Cup (156g)', grams: 156 }],
  },
  {
    id: 'okra',
    name: 'Okra',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 33,
      protein: 1.9,
      carbs: 7,
      fats: 0.2,
    },
    portions: [{ id: 'cup_cooked', label: 'Cup (100g)', grams: 100 }],
  },
  {
    id: 'leek',
    name: 'Leek',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 61,
      protein: 1.5,
      carbs: 14,
      fats: 0.3,
    },
    portions: [{ id: 'cup_cooked', label: 'Cup (89g)', grams: 89 }],
  },
  {
    id: 'sweet_corn_canned',
    name: 'Sweet Corn (Canned, Drained)',
    category: 'carbs',
    subcategory: 'starchy',
    per100g: {
      calories: 67,
      protein: 2.3,
      carbs: 14,
      fats: 1,
    },
    portions: [
      { id: 'half_cup', label: '½ Cup (82g)', grams: 82 },
      { id: 'cup', label: 'Cup (164g)', grams: 164 },
    ],
  },

  // Fats - Oils & Nuts (More)
  {
    id: 'canola_oil',
    name: 'Canola Oil',
    category: 'fats',
    subcategory: 'oil',
    per100g: {
      calories: 884,
      protein: 0,
      carbs: 0,
      fats: 100,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (14g)', grams: 14 }],
  },
  {
    id: 'avocado_oil',
    name: 'Avocado Oil',
    category: 'fats',
    subcategory: 'oil',
    per100g: {
      calories: 884,
      protein: 0,
      carbs: 0,
      fats: 100,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (14g)', grams: 14 }],
  },
  {
    id: 'sesame_oil',
    name: 'Sesame Oil',
    category: 'fats',
    subcategory: 'oil',
    per100g: {
      calories: 884,
      protein: 0,
      carbs: 0,
      fats: 100,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (14g)', grams: 14 }],
  },
  {
    id: 'pistachios',
    name: 'Pistachios',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 562,
      protein: 20,
      carbs: 28,
      fats: 45,
    },
    portions: [{ id: 'one_nut', label: '1 Pistachio (1g)', grams: 1 }],
  },
  {
    id: 'hazelnuts',
    name: 'Hazelnuts',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 628,
      protein: 15,
      carbs: 17,
      fats: 61,
    },
    portions: [{ id: 'one_nut', label: '1 Hazelnut (2g)', grams: 2 }],
  },
  {
    id: 'macadamia_nuts',
    name: 'Macadamia Nuts',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 718,
      protein: 8,
      carbs: 14,
      fats: 76,
    },
    portions: [{ id: 'one_nut', label: '1 Macadamia Nut (2g)', grams: 2 }],
  },
  {
    id: 'brazil_nuts',
    name: 'Brazil Nuts',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 659,
      protein: 14,
      carbs: 12,
      fats: 67,
    },
    portions: [{ id: 'one_nut', label: '1 Brazil Nut (5g)', grams: 5 }],
  },
  {
    id: 'pine_nuts',
    name: 'Pine Nuts',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 673,
      protein: 14,
      carbs: 13,
      fats: 68,
    },
    portions: [{ id: 'one_nut', label: '1 Pine Nut (1g)', grams: 1 }],
  },
  {
    id: 'hemp_seeds',
    name: 'Hemp Seeds',
    category: 'fats',
    subcategory: 'seeds',
    per100g: {
      calories: 553,
      protein: 32,
      carbs: 8,
      fats: 49,
    },
  },
  {
    id: 'sesame_seeds',
    name: 'Sesame Seeds',
    category: 'fats',
    subcategory: 'seeds',
    per100g: {
      calories: 573,
      protein: 18,
      carbs: 23,
      fats: 50,
    },
  },
  {
    id: 'tahini',
    name: 'Tahini (Sesame Paste)',
    category: 'fats',
    subcategory: 'seeds',
    per100g: {
      calories: 595,
      protein: 17,
      carbs: 21,
      fats: 53,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (15g)', grams: 15 }],
  },

  // Carbs - Sweets & Condiments (macros-based)
  {
    id: 'honey',
    name: 'Honey',
    category: 'carbs',
    subcategory: 'sweeteners',
    per100g: {
      calories: 304,
      protein: 0.3,
      carbs: 82,
      fats: 0,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (15g)', grams: 15 }],
  },
  {
    id: 'maple_syrup',
    name: 'Maple Syrup',
    category: 'carbs',
    subcategory: 'sweeteners',
    per100g: {
      calories: 260,
      protein: 0,
      carbs: 67,
      fats: 0,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (15g)', grams: 15 }],
  },
  {
    id: 'jam_strawberry',
    name: 'Jam (Strawberry)',
    category: 'carbs',
    subcategory: 'condiments',
    per100g: {
      calories: 250,
      protein: 0.5,
      carbs: 65,
      fats: 0.2,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (15g)', grams: 15 }],
  },
  {
    id: 'ketchup',
    name: 'Ketchup',
    category: 'carbs',
    subcategory: 'condiments',
    per100g: {
      calories: 112,
      protein: 1.3,
      carbs: 26,
      fats: 0.2,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (15g)', grams: 15 }],
  },
  {
    id: 'mustard',
    name: 'Mustard (Yellow)',
    category: 'carbs',
    subcategory: 'condiments',
    per100g: {
      calories: 66,
      protein: 4.4,
      carbs: 5.8,
      fats: 3.6,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (15g)', grams: 15 }],
  },
  {
    id: 'soy_sauce',
    name: 'Soy Sauce',
    category: 'carbs',
    subcategory: 'condiments',
    per100g: {
      calories: 53,
      protein: 8,
      carbs: 4.9,
      fats: 0.1,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (15g)', grams: 15 }],
  },
  {
    id: 'sriracha',
    name: 'Sriracha Hot Sauce',
    category: 'carbs',
    subcategory: 'condiments',
    per100g: {
      calories: 93,
      protein: 2,
      carbs: 20,
      fats: 1,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (15g)', grams: 15 }],
  },
  {
    id: 'bbq_sauce',
    name: 'BBQ Sauce',
    category: 'carbs',
    subcategory: 'condiments',
    per100g: {
      calories: 165,
      protein: 1.3,
      carbs: 39,
      fats: 0.4,
    },
    portions: [{ id: 'one_tbsp', label: '1 Tbsp (15g)', grams: 15 }],
  },

  // Carbs - Beverages (Non-alcoholic)
  {
    id: 'orange_juice',
    name: 'Orange Juice',
    category: 'carbs',
    subcategory: 'beverages',
    per100g: {
      calories: 45,
      protein: 0.7,
      carbs: 10.4,
      fats: 0.2,
    },
    portions: [{ id: 'cup', label: '1 Cup (248g)', grams: 248 }],
  },
  {
    id: 'apple_juice',
    name: 'Apple Juice',
    category: 'carbs',
    subcategory: 'beverages',
    per100g: {
      calories: 46,
      protein: 0.1,
      carbs: 11.3,
      fats: 0.1,
    },
    portions: [{ id: 'cup', label: '1 Cup (248g)', grams: 248 }],
  },
  {
    id: 'grape_juice',
    name: 'Grape Juice',
    category: 'carbs',
    subcategory: 'beverages',
    per100g: {
      calories: 60,
      protein: 0.4,
      carbs: 14.8,
      fats: 0.1,
    },
    portions: [{ id: 'cup', label: '1 Cup (248g)', grams: 248 }],
  },
  {
    id: 'coca_cola',
    name: 'Coca-Cola (Regular)',
    category: 'carbs',
    subcategory: 'beverages',
    per100g: {
      calories: 39,
      protein: 0,
      carbs: 10.6,
      fats: 0,
    },
    portions: [
      { id: 'can_12oz', label: '12 oz Can/Bottle (355g)', grams: 355 },
      { id: 'bottle_20oz', label: '20 oz Bottle (567g)', grams: 567 },
      { id: 'bottle_2l', label: '2 L Bottle (2000g)', grams: 2000 },
    ],
  },
  {
    id: 'coca_cola_diet',
    name: 'Coca-Cola (Diet)',
    category: 'carbs',
    subcategory: 'beverages',
    per100g: {
      calories: 1,
      protein: 0,
      carbs: 0,
      fats: 0,
    },
    portions: [
      { id: 'can_12oz', label: '12 oz Can/Bottle (355g)', grams: 355 },
      { id: 'bottle_20oz', label: '20 oz Bottle (567g)', grams: 567 },
      { id: 'bottle_2l', label: '2 L Bottle (2000g)', grams: 2000 },
    ],
  },
  {
    id: 'gatorade',
    name: 'Gatorade (Lemon-Lime)',
    category: 'carbs',
    subcategory: 'beverages',
    per100g: {
      calories: 20,
      protein: 0,
      carbs: 5.5,
      fats: 0,
    },
    portions: [
      { id: 'bottle_20oz', label: '20 oz Bottle (567g)', grams: 567 },
      { id: 'bottle_32oz', label: '32 oz Bottle (946g)', grams: 946 },
    ],
  },
  {
    id: 'coconut_water',
    name: 'Coconut Water (Unsweetened)',
    category: 'carbs',
    subcategory: 'beverages',
    per100g: {
      calories: 19,
      protein: 0.7,
      carbs: 3.7,
      fats: 0.2,
    },
    portions: [
      { id: 'one_cup', label: '1 Cup (240g)', grams: 240 },
      { id: 'one_coconut', label: 'From 1 Coconut (400g)', grams: 400 },
    ],
  },
  {
    id: 'coffee_black',
    name: 'Coffee (Black)',
    category: 'carbs',
    subcategory: 'beverages',
    per100g: {
      calories: 1,
      protein: 0.1,
      carbs: 0,
      fats: 0,
    },
    portions: [{ id: 'one_cup', label: '1 Cup (240g)', grams: 240 }],
  },
  {
    id: 'tea_black',
    name: 'Tea (Black)',
    category: 'carbs',
    subcategory: 'beverages',
    per100g: {
      calories: 1,
      protein: 0,
      carbs: 0.3,
      fats: 0,
    },
  },

  // Alcoholic Beverages
  {
    id: 'beer_lager',
    name: 'Beer (Lager, 5%)',
    category: 'carbs',
    subcategory: 'alcohol',
    per100g: {
      calories: 43,
      protein: 0.5,
      carbs: 3.6,
      fats: 0,
    },
    portions: [
      { id: 'can_12oz', label: '12 oz Can/Bottle (355g)', grams: 355 },
      { id: 'pint_16oz', label: '16 oz Pint (473g)', grams: 473 },
    ],
  },
  {
    id: 'wine_red',
    name: 'Wine (Red, 13%)',
    category: 'carbs',
    subcategory: 'alcohol',
    per100g: {
      calories: 85,
      protein: 0.1,
      carbs: 2.7,
      fats: 0,
    },
    portions: [{ id: 'glass_5oz', label: '5 oz Glass (147g)', grams: 147 }],
  },
  {
    id: 'wine_white',
    name: 'Wine (White, 12%)',
    category: 'carbs',
    subcategory: 'alcohol',
    per100g: {
      calories: 82,
      protein: 0.1,
      carbs: 2.6,
      fats: 0,
    },
    portions: [{ id: 'glass_5oz', label: '5 oz Glass (147g)', grams: 147 }],
  },
  {
    id: 'vodka_40',
    name: 'Vodka (40%)',
    category: 'carbs',
    subcategory: 'alcohol',
    per100g: {
      calories: 231,
      protein: 0,
      carbs: 0,
      fats: 0,
    },
    portions: [{ id: 'shot_1_5oz', label: '1.5 oz Shot (42g)', grams: 42 }],
  },

  // Supplements (More)
  {
    id: 'bcaa_powder',
    name: 'BCAA Powder',
    category: 'supplements',
    subcategory: 'amino_acids',
    per100g: {
      calories: 400,
      protein: 90,
      carbs: 5,
      fats: 0.5,
    },
    portions: [{ id: 'scoop', label: '1 Scoop (10g)', grams: 10 }],
  },
  {
    id: 'preworkout_powder',
    name: 'Pre-Workout Powder',
    category: 'supplements',
    subcategory: 'other',
    per100g: {
      calories: 200,
      protein: 0,
      carbs: 50,
      fats: 0,
    },
    portions: [{ id: 'scoop', label: '1 Scoop (10g)', grams: 10 }],
  },
  {
    id: 'fish_oil_capsules',
    name: 'Fish Oil (Capsules)',
    category: 'supplements',
    subcategory: 'omega',
    per100g: {
      calories: 900,
      protein: 0,
      carbs: 0,
      fats: 100,
    },
    portions: [{ id: 'one_capsule', label: '1 Capsule (1g)', grams: 1 }],
  },
  {
    id: 'electrolyte_mix',
    name: 'Electrolyte Mix (Powder)',
    category: 'supplements',
    subcategory: 'other',
    per100g: {
      calories: 120,
      protein: 0,
      carbs: 30,
      fats: 0,
    },
    portions: [{ id: 'scoop', label: '1 Scoop (10g)', grams: 10 }],
  },
  {
    id: 'collagen_peptides',
    name: 'Collagen Peptides',
    category: 'supplements',
    subcategory: 'protein',
    per100g: {
      calories: 360,
      protein: 90,
      carbs: 0,
      fats: 0,
    },
    portions: [{ id: 'scoop', label: '1 Scoop (30g)', grams: 30 }],
  },
  {
    id: 'pea_protein',
    name: 'Pea Protein Powder',
    category: 'supplements',
    subcategory: 'protein',
    per100g: {
      calories: 390,
      protein: 80,
      carbs: 5,
      fats: 6,
    },
    portions: [{ id: 'scoop', label: '1 Scoop (30g)', grams: 30 }],
  },

  // Cooked Egg Variations
  {
    id: 'egg_boiled',
    name: 'Egg (Boiled)',
    category: 'protein',
    subcategory: 'eggs',
    per100g: {
      calories: 155,
      protein: 13,
      carbs: 1.1,
      fats: 11,
    },
    portions: [{ id: 'large', label: '1 Large Boiled Egg (50g)', grams: 50 }],
  },
  {
    id: 'egg_fried',
    name: 'Egg (Fried)',
    category: 'protein',
    subcategory: 'eggs',
    per100g: {
      calories: 196,
      protein: 14,
      carbs: 0.8,
      fats: 15,
    },
    portions: [{ id: 'large', label: '1 Large Fried Egg (46g)', grams: 46 }],
  },
  {
    id: 'egg_scrambled',
    name: 'Egg (Scrambled)',
    category: 'protein',
    subcategory: 'eggs',
    per100g: {
      calories: 149,
      protein: 10,
      carbs: 1.6,
      fats: 11,
    },
    portions: [{ id: 'one_egg', label: 'From 1 Large Egg (~61g)', grams: 61 }],
  },
  {
    id: 'egg_omelette_plain',
    name: 'Omelette (Plain)',
    category: 'protein',
    subcategory: 'eggs',
    per100g: {
      calories: 154,
      protein: 11,
      carbs: 1,
      fats: 11,
    },
    portions: [{ id: 'one_egg', label: 'From 1 Large Egg (~61g)', grams: 61 }],
  },

  // Cooked Meat & Fish Variations
  {
    id: 'chicken_breast_grilled',
    name: 'Chicken Breast (Grilled)',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fats: 3.6,
    },
    portions: [{ id: 'one_piece', label: '1 Piece (120g)', grams: 120 }],
  },
  {
    id: 'chicken_breast_fried',
    name: 'Chicken Breast (Fried, Breaded)',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 220,
      protein: 28,
      carbs: 10,
      fats: 7,
    },
    portions: [{ id: 'one_piece', label: '1 Piece (120g)', grams: 120 }],
  },
  {
    id: 'salmon_smoked',
    name: 'Salmon (Smoked)',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 117,
      protein: 18,
      carbs: 0,
      fats: 4.3,
    },
    portions: [{ id: 'slice', label: '1 Slice (28g)', grams: 28 }],
  },
  {
    id: 'tuna_salad',
    name: 'Tuna Salad',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 198,
      protein: 12,
      carbs: 6,
      fats: 14,
    },
  },
  {
    id: 'meatballs_beef',
    name: 'Meatballs (Beef)',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 280,
      protein: 18,
      carbs: 8,
      fats: 19,
    },
    portions: [{ id: 'one_meatball', label: '1 Meatball (28g)', grams: 28 }],
  },

  // Cooked Vegetable & Carb Variations
  {
    id: 'mashed_potatoes',
    name: 'Mashed Potatoes',
    category: 'carbs',
    subcategory: 'potato',
    per100g: {
      calories: 83,
      protein: 1.7,
      carbs: 18,
      fats: 0.9,
    },
    portions: [{ id: 'one_cup', label: '1 Cup (210g)', grams: 210 }],
  },
  {
    id: 'roasted_potatoes',
    name: 'Roasted Potatoes',
    category: 'carbs',
    subcategory: 'potato',
    per100g: {
      calories: 140,
      protein: 2.5,
      carbs: 25,
      fats: 3.5,
    },
    portions: [{ id: 'one_cup', label: '1 Cup (150g)', grams: 150 }],
  },
  {
    id: 'broccoli_steamed',
    name: 'Broccoli (Steamed)',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 35,
      protein: 2.4,
      carbs: 7,
      fats: 0.4,
    },
    portions: [{ id: 'one_cup', label: '1 Cup (156g)', grams: 156 }],
  },
  {
    id: 'carrots_cooked',
    name: 'Carrots (Cooked, Boiled)',
    category: 'vegetables',
    subcategory: 'root',
    per100g: {
      calories: 35,
      protein: 0.8,
      carbs: 8,
      fats: 0.2,
    },
    portions: [{ id: 'one_cup', label: '1 Cup (156g)', grams: 156 }],
  },
  {
    id: 'spinach_cooked',
    name: 'Spinach (Cooked, Boiled)',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 23,
      protein: 3,
      carbs: 3.6,
      fats: 0.3,
    },
    portions: [{ id: 'one_cup', label: '1 Cup (180g)', grams: 180 }],
  },
];

export const FOOD_CATEGORIES = {
  protein: { label: 'Proteins', color: 'red' },
  carbs: { label: 'Carbs', color: 'amber' },
  vegetables: { label: 'Vegetables', color: 'green' },
  fats: { label: 'Fats', color: 'yellow' },
  supplements: { label: 'Supplements', color: 'purple' },
};

// Helper to search foods
export const searchFoods = (query) => {
  if (!query || query.trim().length === 0) {
    return FOOD_DATABASE;
  }

  const lowerQuery = query.toLowerCase();
  return FOOD_DATABASE.filter((food) =>
    food.name.toLowerCase().includes(lowerQuery)
  );
};

// Helper to get food by ID
export const getFoodById = (id) => {
  return FOOD_DATABASE.find((food) => food.id === id);
};
