// Food database with nutritional information per 100g
// All values are per 100 grams of the food item

export const FOOD_DATABASE = [
  // Proteins - Meat
  {
    id: 'chicken_breast',
    name: 'Chicken Breast',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 165,
      protein: 31,
      carbs: 0,
      fats: 3.6,
    },
  },
  {
    id: 'chicken_thigh',
    name: 'Chicken Thigh',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 209,
      protein: 26,
      carbs: 0,
      fats: 10.9,
    },
  },
  {
    id: 'turkey_breast',
    name: 'Turkey Breast',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 135,
      protein: 30,
      carbs: 0,
      fats: 1,
    },
  },
  {
    id: 'ground_turkey_93_7',
    name: 'Ground Turkey (93/7)',
    category: 'protein',
    subcategory: 'poultry',
    per100g: {
      calories: 170,
      protein: 21,
      carbs: 0,
      fats: 9,
    },
  },
  {
    id: 'ground_beef',
    name: 'Ground Beef (80/20)',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 254,
      protein: 17.2,
      carbs: 0,
      fats: 20,
    },
  },
  {
    id: 'ground_beef_lean',
    name: 'Ground Beef (90/10)',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 176,
      protein: 20,
      carbs: 0,
      fats: 10,
    },
  },
  {
    id: 'steak_sirloin',
    name: 'Sirloin Steak',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 271,
      protein: 25,
      carbs: 0,
      fats: 18,
    },
  },
  {
    id: 'steak_filet_mignon',
    name: 'Filet Mignon Steak',
    category: 'protein',
    subcategory: 'beef',
    per100g: {
      calories: 276,
      protein: 24,
      carbs: 0,
      fats: 19,
    },
  },
  {
    id: 'salmon',
    name: 'Salmon',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 208,
      protein: 20,
      carbs: 0,
      fats: 13,
    },
  },
  {
    id: 'tuna',
    name: 'Tuna',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 144,
      protein: 30,
      carbs: 0,
      fats: 1,
    },
  },
  {
    id: 'tilapia',
    name: 'Tilapia',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 129,
      protein: 26,
      carbs: 0,
      fats: 2.7,
    },
  },
  {
    id: 'cod',
    name: 'Cod',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 82,
      protein: 18,
      carbs: 0,
      fats: 0.7,
    },
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    category: 'protein',
    subcategory: 'fish',
    per100g: {
      calories: 99,
      protein: 24,
      carbs: 0.2,
      fats: 0.3,
    },
  },
  {
    id: 'pork_chop',
    name: 'Pork Chop',
    category: 'protein',
    subcategory: 'pork',
    per100g: {
      calories: 231,
      protein: 25.7,
      carbs: 0,
      fats: 13.9,
    },
  },
  {
    id: 'bacon_cooked',
    name: 'Bacon (Cooked)',
    category: 'protein',
    subcategory: 'pork',
    per100g: {
      calories: 541,
      protein: 37,
      carbs: 1.4,
      fats: 42,
    },
  },

  // Proteins - Eggs & Dairy
  {
    id: 'eggs_whole',
    name: 'Whole Eggs',
    category: 'protein',
    subcategory: 'eggs',
    per100g: {
      calories: 155,
      protein: 13,
      carbs: 1.1,
      fats: 11,
    },
  },
  {
    id: 'egg_whites',
    name: 'Egg Whites',
    category: 'protein',
    subcategory: 'eggs',
    per100g: {
      calories: 52,
      protein: 11,
      carbs: 0.7,
      fats: 0.2,
    },
  },
  {
    id: 'greek_yogurt',
    name: 'Greek Yogurt (Non-fat)',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 59,
      protein: 10,
      carbs: 3.6,
      fats: 0.4,
    },
  },
  {
    id: 'cottage_cheese',
    name: 'Cottage Cheese (Low-fat)',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 72,
      protein: 12,
      carbs: 4.3,
      fats: 1,
    },
  },
  {
    id: 'milk_whole',
    name: 'Whole Milk',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 61,
      protein: 3.2,
      carbs: 4.8,
      fats: 3.3,
    },
  },
  {
    id: 'milk_skim',
    name: 'Skim Milk',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 34,
      protein: 3.4,
      carbs: 5,
      fats: 0.1,
    },
  },
  {
    id: 'milk_almond',
    name: 'Almond Milk (Unsweetened)',
    category: 'protein',
    subcategory: 'dairy-alt',
    per100g: {
      calories: 13,
      protein: 0.4,
      carbs: 0.6,
      fats: 1.1,
    },
  },
  {
    id: 'cheese_cheddar',
    name: 'Cheddar Cheese',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 403,
      protein: 25,
      carbs: 1.3,
      fats: 33,
    },
  },
  {
    id: 'cheese_mozzarella',
    name: 'Mozzarella Cheese',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 280,
      protein: 28,
      carbs: 2.2,
      fats: 17,
    },
  },
  {
    id: 'cheese_parmesan',
    name: 'Parmesan Cheese',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 431,
      protein: 38,
      carbs: 4.1,
      fats: 29,
    },
  },
  {
    id: 'cheese_swiss',
    name: 'Swiss Cheese',
    category: 'protein',
    subcategory: 'dairy',
    per100g: {
      calories: 380,
      protein: 27,
      carbs: 5.4,
      fats: 28,
    },
  },

  // Proteins - Plant-Based
  {
    id: 'tofu_firm',
    name: 'Tofu (Firm)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 76,
      protein: 8,
      carbs: 3,
      fats: 5,
    },
  },
  {
    id: 'tempeh',
    name: 'Tempeh',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 193,
      protein: 19,
      carbs: 9,
      fats: 11,
    },
  },
  {
    id: 'lentils_cooked',
    name: 'Lentils (Cooked)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 116,
      protein: 9,
      carbs: 20,
      fats: 0.4,
    },
  },
  {
    id: 'chickpeas_cooked',
    name: 'Chickpeas (Cooked)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 164,
      protein: 9,
      carbs: 27,
      fats: 2.6,
    },
  },
  {
    id: 'black_beans_cooked',
    name: 'Black Beans (Cooked)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 132,
      protein: 8.9,
      carbs: 24,
      fats: 0.5,
    },
  },
  {
    id: 'kidney_beans_cooked',
    name: 'Kidney Beans (Cooked)',
    category: 'protein',
    subcategory: 'plant-based',
    per100g: {
      calories: 127,
      protein: 8.7,
      carbs: 23,
      fats: 0.5,
    },
  },

  // Carbs - Grains
  {
    id: 'white_rice_cooked',
    name: 'White Rice (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 130,
      protein: 2.7,
      carbs: 28,
      fats: 0.3,
    },
  },
  {
    id: 'brown_rice_cooked',
    name: 'Brown Rice (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 112,
      protein: 2.6,
      carbs: 24,
      fats: 0.9,
    },
  },
  {
    id: 'pasta_cooked',
    name: 'Pasta (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 131,
      protein: 5,
      carbs: 25,
      fats: 1.1,
    },
  },
  {
    id: 'quinoa_cooked',
    name: 'Quinoa (Cooked)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 120,
      protein: 4.4,
      carbs: 21,
      fats: 1.9,
    },
  },
  {
    id: 'oats_dry',
    name: 'Oats (Dry)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 389,
      protein: 16.9,
      carbs: 66,
      fats: 6.9,
    },
  },
  {
    id: 'cereal_corn_flakes',
    name: 'Cereal (Corn Flakes)',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 357,
      protein: 7.5,
      carbs: 84,
      fats: 0.4,
    },
  },
  {
    id: 'granola',
    name: 'Granola',
    category: 'carbs',
    subcategory: 'grains',
    per100g: {
      calories: 471,
      protein: 10,
      carbs: 64,
      fats: 20,
    },
  },
  {
    id: 'bread_white',
    name: 'White Bread',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 265,
      protein: 9,
      carbs: 49,
      fats: 3.2,
    },
  },
  {
    id: 'bread_whole_wheat',
    name: 'Whole Wheat Bread',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 247,
      protein: 13,
      carbs: 41,
      fats: 3.4,
    },
  },
  {
    id: 'bagel_plain',
    name: 'Bagel (Plain)',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 250,
      protein: 10,
      carbs: 49,
      fats: 1.5,
    },
  },
  {
    id: 'tortilla_flour',
    name: 'Tortilla (Flour)',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 300,
      protein: 8,
      carbs: 50,
      fats: 7,
    },
  },
  {
    id: 'tortilla_corn',
    name: 'Tortilla (Corn)',
    category: 'carbs',
    subcategory: 'bread',
    per100g: {
      calories: 218,
      protein: 5.7,
      carbs: 45,
      fats: 2.8,
    },
  },

  // Carbs - Potatoes & Starchy Veg
  {
    id: 'potato_baked',
    name: 'Baked Potato',
    category: 'carbs',
    subcategory: 'potato',
    per100g: {
      calories: 93,
      protein: 2.5,
      carbs: 21,
      fats: 0.1,
    },
  },
  {
    id: 'sweet_potato',
    name: 'Sweet Potato',
    category: 'carbs',
    subcategory: 'potato',
    per100g: {
      calories: 86,
      protein: 1.6,
      carbs: 20,
      fats: 0.1,
    },
  },
  {
    id: 'french_fries_baked',
    name: 'French Fries (Baked)',
    category: 'carbs',
    subcategory: 'potato',
    per100g: {
      calories: 150,
      protein: 2.5,
      carbs: 26,
      fats: 4.5,
    },
  },
  {
    id: 'corn_sweet_cooked',
    name: 'Corn (Sweet, Cooked)',
    category: 'carbs',
    subcategory: 'starchy',
    per100g: {
      calories: 86,
      protein: 3.2,
      carbs: 19,
      fats: 1.2,
    },
  },
  {
    id: 'peas_green_cooked',
    name: 'Peas (Green, Cooked)',
    category: 'carbs',
    subcategory: 'starchy',
    per100g: {
      calories: 81,
      protein: 5,
      carbs: 14,
      fats: 0.4,
    },
  },

  // Fruits
  {
    id: 'banana',
    name: 'Banana',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 89,
      protein: 1.1,
      carbs: 23,
      fats: 0.3,
    },
  },
  {
    id: 'apple',
    name: 'Apple',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 52,
      protein: 0.3,
      carbs: 14,
      fats: 0.2,
    },
  },
  {
    id: 'orange',
    name: 'Orange',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 47,
      protein: 0.9,
      carbs: 12,
      fats: 0.1,
    },
  },
  {
    id: 'strawberries',
    name: 'Strawberries',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 32,
      protein: 0.7,
      carbs: 8,
      fats: 0.3,
    },
  },
  {
    id: 'blueberries',
    name: 'Blueberries',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 57,
      protein: 0.7,
      carbs: 14,
      fats: 0.3,
    },
  },
  {
    id: 'grapes',
    name: 'Grapes',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 69,
      protein: 0.7,
      carbs: 18,
      fats: 0.2,
    },
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 30,
      protein: 0.6,
      carbs: 8,
      fats: 0.2,
    },
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 50,
      protein: 0.5,
      carbs: 13,
      fats: 0.1,
    },
  },
  {
    id: 'mango',
    name: 'Mango',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 60,
      protein: 0.8,
      carbs: 15,
      fats: 0.4,
    },
  },
  {
    id: 'raspberries',
    name: 'Raspberries',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 52,
      protein: 1.2,
      carbs: 12,
      fats: 0.7,
    },
  },
  {
    id: 'kiwi',
    name: 'Kiwi',
    category: 'carbs',
    subcategory: 'fruit',
    per100g: {
      calories: 61,
      protein: 1.1,
      carbs: 15,
      fats: 0.5,
    },
  },

  // Vegetables
  {
    id: 'broccoli',
    name: 'Broccoli',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 34,
      protein: 2.8,
      carbs: 7,
      fats: 0.4,
    },
  },
  {
    id: 'spinach',
    name: 'Spinach',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 23,
      protein: 2.9,
      carbs: 3.6,
      fats: 0.4,
    },
  },
  {
    id: 'asparagus',
    name: 'Asparagus',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 20,
      protein: 2.2,
      carbs: 3.9,
      fats: 0.1,
    },
  },
  {
    id: 'green_beans',
    name: 'Green Beans',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 31,
      protein: 1.8,
      carbs: 7,
      fats: 0.1,
    },
  },
  {
    id: 'lettuce_romaine',
    name: 'Lettuce (Romaine)',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 17,
      protein: 1.2,
      carbs: 3.3,
      fats: 0.3,
    },
  },
  {
    id: 'lettuce_iceberg',
    name: 'Lettuce (Iceberg)',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 14,
      protein: 0.9,
      carbs: 3,
      fats: 0.1,
    },
  },
  {
    id: 'kale',
    name: 'Kale',
    category: 'vegetables',
    subcategory: 'green',
    per100g: {
      calories: 49,
      protein: 4.3,
      carbs: 9,
      fats: 0.9,
    },
  },
  {
    id: 'carrots',
    name: 'Carrots',
    category: 'vegetables',
    subcategory: 'root',
    per100g: {
      calories: 41,
      protein: 0.9,
      carbs: 10,
      fats: 0.2,
    },
  },
  {
    id: 'onion',
    name: 'Onion',
    category: 'vegetables',
    subcategory: 'root',
    per100g: {
      calories: 40,
      protein: 1.1,
      carbs: 9,
      fats: 0.1,
    },
  },
  {
    id: 'tomatoes',
    name: 'Tomatoes',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 18,
      protein: 0.9,
      carbs: 3.9,
      fats: 0.2,
    },
  },
  {
    id: 'bell_pepper',
    name: 'Bell Pepper',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 31,
      protein: 1,
      carbs: 6,
      fats: 0.3,
    },
  },
  {
    id: 'cucumber',
    name: 'Cucumber',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 15,
      protein: 0.7,
      carbs: 3.6,
      fats: 0.1,
    },
  },
  {
    id: 'mushrooms_white',
    name: 'Mushrooms (White)',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 22,
      protein: 3.1,
      carbs: 3.3,
      fats: 0.3,
    },
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 17,
      protein: 1.2,
      carbs: 3.1,
      fats: 0.3,
    },
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    category: 'vegetables',
    subcategory: 'other',
    per100g: {
      calories: 25,
      protein: 1.9,
      carbs: 5,
      fats: 0.3,
    },
  },

  // Fats
  {
    id: 'avocado',
    name: 'Avocado',
    category: 'fats',
    subcategory: 'fruit',
    per100g: {
      calories: 160,
      protein: 2,
      carbs: 9,
      fats: 15,
    },
  },
  {
    id: 'olives_black',
    name: 'Olives (Black)',
    category: 'fats',
    subcategory: 'fruit',
    per100g: {
      calories: 115,
      protein: 0.8,
      carbs: 6,
      fats: 11,
    },
  },
  {
    id: 'olive_oil',
    name: 'Olive Oil',
    category: 'fats',
    subcategory: 'oil',
    per100g: {
      calories: 884,
      protein: 0,
      carbs: 0,
      fats: 100,
    },
  },
  {
    id: 'coconut_oil',
    name: 'Coconut Oil',
    category: 'fats',
    subcategory: 'oil',
    per100g: {
      calories: 890,
      protein: 0,
      carbs: 0,
      fats: 100,
    },
  },
  {
    id: 'butter',
    name: 'Butter',
    category: 'fats',
    subcategory: 'dairy',
    per100g: {
      calories: 717,
      protein: 0.9,
      carbs: 0.1,
      fats: 81,
    },
  },
  {
    id: 'cream_cheese',
    name: 'Cream Cheese',
    category: 'fats',
    subcategory: 'dairy',
    per100g: {
      calories: 342,
      protein: 6,
      carbs: 4,
      fats: 34,
    },
  },
  {
    id: 'sour_cream_full_fat',
    name: 'Sour Cream (Full Fat)',
    category: 'fats',
    subcategory: 'dairy',
    per100g: {
      calories: 198,
      protein: 2.4,
      carbs: 4.6,
      fats: 19,
    },
  },
  {
    id: 'mayonnaise',
    name: 'Mayonnaise',
    category: 'fats',
    subcategory: 'other',
    per100g: {
      calories: 700,
      protein: 1,
      carbs: 0.6,
      fats: 75,
    },
  },
  {
    id: 'almonds',
    name: 'Almonds',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 579,
      protein: 21,
      carbs: 22,
      fats: 50,
    },
  },
  {
    id: 'peanut_butter',
    name: 'Peanut Butter',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 588,
      protein: 25,
      carbs: 20,
      fats: 50,
    },
  },
  {
    id: 'walnuts',
    name: 'Walnuts',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 654,
      protein: 15,
      carbs: 14,
      fats: 65,
    },
  },
  {
    id: 'cashews',
    name: 'Cashews',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 553,
      protein: 18,
      carbs: 30,
      fats: 44,
    },
  },
  {
    id: 'pecans',
    name: 'Pecans',
    category: 'fats',
    subcategory: 'nuts',
    per100g: {
      calories: 691,
      protein: 9,
      carbs: 14,
      fats: 72,
    },
  },
  {
    id: 'chia_seeds',
    name: 'Chia Seeds',
    category: 'fats',
    subcategory: 'seeds',
    per100g: {
      calories: 486,
      protein: 17,
      carbs: 42,
      fats: 31,
    },
  },
  {
    id: 'flax_seeds',
    name: 'Flax Seeds',
    category: 'fats',
    subcategory: 'seeds',
    per100g: {
      calories: 534,
      protein: 18,
      carbs: 29,
      fats: 42,
    },
  },
  {
    id: 'pumpkin_seeds',
    name: 'Pumpkin Seeds',
    category: 'fats',
    subcategory: 'seeds',
    per100g: {
      calories: 559,
      protein: 30,
      carbs: 11,
      fats: 49,
    },
  },
  {
    id: 'sunflower_seeds',
    name: 'Sunflower Seeds',
    category: 'fats',
    subcategory: 'seeds',
    per100g: {
      calories: 584,
      protein: 21,
      carbs: 20,
      fats: 51,
    },
  },

  // Protein Supplements
  {
    id: 'whey_protein',
    name: 'Whey Protein Powder',
    category: 'supplements',
    subcategory: 'protein',
    per100g: {
      calories: 400,
      protein: 80,
      carbs: 8,
      fats: 5,
    },
  },
  {
    id: 'casein_protein',
    name: 'Casein Protein Powder',
    category: 'supplements',
    subcategory: 'protein',
    per100g: {
      calories: 360,
      protein: 78,
      carbs: 5,
      fats: 2,
    },
  },
  {
    id: 'soy_protein_isolate',
    name: 'Soy Protein Isolate',
    category: 'supplements',
    subcategory: 'protein',
    per100g: {
      calories: 335,
      protein: 88,
      carbs: 0.4,
      fats: 0.5,
    },
  },
  {
    id: 'creatine_monohydrate',
    name: 'Creatine Monohydrate',
    category: 'supplements',
    subcategory: 'other',
    per100g: {
      calories: 0,
      protein: 0,
      carbs: 0,
      fats: 0,
    },
  },
];

export const FOOD_CATEGORIES = {
  protein: { label: 'Proteins', color: 'red' },
  carbs: { label: 'Carbs', color: 'amber' },
  vegetables: { label: 'Vegetables', color: 'green' },
  fats: { label: 'Fats', color: 'yellow' },
  supplements: { label: 'Supplements', color: 'purple' },
};

// Helper to search foods
export const searchFoods = (query) => {
  if (!query || query.trim().length === 0) {
    return FOOD_DATABASE;
  }

  const lowerQuery = query.toLowerCase();
  return FOOD_DATABASE.filter((food) =>
    food.name.toLowerCase().includes(lowerQuery)
  );
};

// Helper to get food by ID
export const getFoodById = (id) => {
  return FOOD_DATABASE.find((food) => food.id === id);
};
